const assert=require('assert');const fs=require('fs');
const air=fs.readFileSync('ai_portfolio_review.gs','utf8');
const sec=fs.readFileSync('分析/秘書.js','utf8');
const core=fs.readFileSync('コア/コード.js','utf8');
const ui=fs.readFileSync('_github_HAKSAI-Central/index.html','utf8');
assert(air.includes("const AIR_RUNS_SHEET = 'ReviewRuns'"));
assert(air.includes("stockout_risk:'STOCKOUT_RISK'"));
assert(air.includes("home_replenishment:'HOME_REPLENISHMENT'"));
assert(air.includes("acos_over_breakeven:'AD_LOSS'"));
assert(air.includes("cvr_drop:'CVR_DROP'"));
assert(air.includes('secretary_voice'));
assert(air.includes('airValidate_'));
assert(air.includes("source:'ai_review'"));
assert(sec.includes("'source','review_run_id','dedupe_key'"));
assert(!sec.includes("category:'朝礼'"));
assert(core.includes("runAiPortfolioReview_({ trigger:'manual' })"));
assert(ui.includes('今日の焦点'));
assert(ui.includes('全体相談Markdown'));
assert(ui.includes('商品ページPDFをAI診断'));
console.log('ai_portfolio_review_test: ok');
