const assert=require('assert');const fs=require('fs');
const core=fs.readFileSync('コア/コード.js','utf8');const ui=fs.readFileSync('_github_HAKSAI-Central/index.html','utf8');const lf=fs.readFileSync('listing_feedback.gs','utf8');
assert(core.includes("document_role: 'consultation_brief'"));
assert(core.includes("consultation_memo: ''"));
assert(core.includes('research_lineage: { competitor_asins:'));
assert(ui.includes('ページ制作相談ブリーフ'));
assert(ui.includes('人間の相談メモ'));
assert(ui.includes('このままAmazonの商品説明・画像文言・入稿情報として使用してはいけません'));
assert(ui.includes('仮の商品コンセプト'));
assert(ui.includes('GPTへの回答ルール'));
assert(ui.includes('HAKSAI_ページ制作相談ブリーフ_'));
assert(ui.includes("addEventListener('click', () => downloadCurrentPageProjectMarkdown(false))"), 'download must not receive the click event as copyOnly');
assert(ui.includes('競合ベンチマーク商品'));
assert(ui.includes("consultationHandoff.available_variations"));
assert(ui.includes("consultationHandoff.sku_status = 'undecided'"));
assert(ui.includes("delete consultationHandoff.ready"));
assert(lf.includes("const LF_SNAPSHOT_SHEET = 'listing_snapshots'"));
assert(lf.includes('競合ASINを自社ASINとして登録できません'));
assert(lf.includes('primary_asin')&&lf.includes('parent_asin')&&lf.includes('child_asins'));
assert(core.includes("action === 'saveOwnListingLink'"));
console.log('consultation_feedback_test: ok');
